GET https://carbide-bongo-338115.et.r.appspot.com/api/simulations/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2NDI2MDI3NTh9.YTU54HqEbc00xSZGhAH_flkXDTD1U4B7IjxPVxx9TcU
###
GET https://carbide-bongo-338115.et.r.appspot.com/api/simulations/296b53f5-ec49-4c06-83d7-00dbba081a77
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2NDI2MDI3NTh9.YTU54HqEbc00xSZGhAH_flkXDTD1U4B7IjxPVxx9TcU
###
POST https://carbide-bongo-338115.et.r.appspot.com/api/simulations/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2NDI2MDI3NTh9.YTU54HqEbc00xSZGhAH_flkXDTD1U4B7IjxPVxx9TcU
Content-Type: application/json

{
    "simulationType": "double action",
    "goodsType": "Elastis",
    "goodsName": "laptop",
    "goodsPic": "https://via.placeholder.com/800x600",
    "inflationType": "Inflasi Tinggi",
    "participantNumber": 4,
    "timer": 5,
    "seller": [
        {
            "unitCost": 1000
        },
        {
            "unitCost": 2000
        }
    ],
    "buyer": [
        {
            "unitValue": 3000
        },
        {
            "unitValue": 4000
        }
    ]
}

###
GET https://carbide-bongo-338115.et.r.appspot.com/api/sessions/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2NDI2MDI3NTh9.YTU54HqEbc00xSZGhAH_flkXDTD1U4B7IjxPVxx9TcU
###
POST https://carbide-bongo-338115.et.r.appspot.com/api/simulations/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2NDI2MDI3NTh9.YTU54HqEbc00xSZGhAH_flkXDTD1U4B7IjxPVxx9TcU
Content-Type: application/json

{
    "simulationType": "double action",
    "goodsType": "Elastis",
    "goodsName": "laptop",
    "goodsPic": "https://via.placeholder.com/800x600",
    "inflationType": "Inflasi Tinggi",
    "participantNumber": 4,
    "timer": 5,
    "seller": [
        {
            "unitCost": 1000
        },
        {
            "unitCost": 2000
        }
    ],
    "buyer": [
        {
            "unitValue": 3000
        },
        {
            "unitValue": 4000
        }
    ]
}