GET http://localhost:8000/api/simulations/
###
POST http://localhost:8000/api/simulations/
Content-Type: application/json

{
    "simulationType": "double action",
    "goodsType": "Elastis",
    "goodsName": "laptop",
    "goodsPic": "https://via.placeholder.com/800x600",
    "inflationType": "Inflasi Tinggi",
    "participantNumber": 4,
    "timer": 5,
    "seller": [
        {
            "unitCost": 1000
        },
        {
            "unitCost": 2000
        }
    ],
    "buyer": [
        {
            "unitValue": 3000
        },
        {
            "unitValue": 4000
        }
    ]
}

###
GET http://localhost:8000/api/sessions/
###
POST http://localhost:8000/api/simulations/
Content-Type: application/json

{
    "simulationType": "double action",
    "goodsType": "Elastis",
    "goodsName": "laptop",
    "goodsPic": "https://via.placeholder.com/800x600",
    "inflationType": "Inflasi Tinggi",
    "participantNumber": 4,
    "timer": 5,
    "seller": [
        {
            "unitCost": 1000
        },
        {
            "unitCost": 2000
        }
    ],
    "buyer": [
        {
            "unitValue": 3000
        },
        {
            "unitValue": 4000
        }
    ]
}